services:
  docker-networks:
    image: gitea.g4f.be/bart/docker-networks
    container_name: docker-networks
    network_mode: bridge # join default bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 6687:80
    networks:
      - revproxy-net
    # command: chown lighttpd:lighttpd /var/run/docker.sock
    tty: true

networks:
  revproxy-net:
    external: true
